sudo: false

language: node_js
node_js:
  - "6"
  - "8"
  - "10"

cache:
  directories:
    - node_modules

env:
  - DIALECT=mysql
  - DIALECT=postgres

services:
  - mysql
addons:
  postgresql: "9.4"

before_script:
  - if [[ "$DIALECT" == "postgres" ]]; then psql -c "drop database if exists test;" -U postgres; fi
  - if [[ "$DIALECT" == "postgres" ]]; then psql -c "create database test;" -U postgres; fi
  - if [[ "$DIALECT" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS test;" -uroot; fi

script:
  - "npm run lint && npm run cover"
  - "bash <(curl -s https://codecov.io/bash) -f coverage/lcov.info"

notifications:
  email: false